apiVersion: finops.krateo.io/v1
kind: DatabaseConfig
metadata:
  name: # DatabaseConfig name
  namespace: # DatabaseConfig namespace
spec:
  host: # host name for the database
  token: # object reference to secret with key bearer-token
    name: # secret name
    namespace: # secret namespace
  clusterName: # generic compute cluster name
  notebookPath: # path to the notebook 
---
apiVersion: finops.krateo.io/v1
kind: FocusConfig
metadata:
  name: # FocusConfig name
  namespace: # FocusConfig namespace
spec:
  scraperConfig: # same fields as krateoplatformops/finops-prometheus-scraper-generic
    tableName: # tableName in the database to upload the data to
    # url: # path to the exporter, optional (if missing, its taken from the exporter)
    pollingIntervalHours: # int
    scraperDatabaseConfigRef: # See above kind DatabaseConfig
      name: # name of the databaseConfigRef CR 
      namespace: # namespace of the databaseConfigRef CR
  focusSpec: # See FOCUS for field details
    availabilityZone:
    billedCost:
    billingAccountId:
    billingAccountName:
    billingCurrency:
    billingPeriodEnd:
    billingPeriodStart:
    chargeCategory:
    chargeClass:
    chargeDescription:
    chargeFrequency:
    chargePeriodEnd:
    chargePeriodStart:
    commitmentDiscountCategory:
    commitmentDiscountName:
    commitmentDiscountStatus:
    commitmentDiscountType:
    commitmentDiscoutId:
    consumedQuantity:
    consumedUnit:
    contractedCost:
    contractedUnitCost:
    effectiveCost:
    invoiceIssuerName:
    listCost:
    listUnitPrice:
    pricingCategory:
    pricingQuantity:
    pricingUnit:
    providerName:
    publisherName:
    regionId:
    regionName:
    resourceId:
    resourceName:
    resourceType:
    serviceCategory:
    serviceName:
    skuId:
    skuPriceId:
    subAccountId:
    subAccountName:
    tags:
      - key:
        value: