apiVersion: finops.krateo.io/v1
kind: DatabaseConfig
metadata:
  name: # config name
  namespace: default
spec:
  host: # host name for the database
  token: # access token
  clusterName: # generic compute cluster name
  notebookPath: # path to the notebook 
---
apiVersion: finops.krateo.io/v1
kind: FocusConfig
metadata:
  labels:
    app.kubernetes.io/name: focusconfig
    app.kubernetes.io/instance: focusconfig-sample
    app.kubernetes.io/part-of: operator-focus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator-focus
  name: focusconfig-sample2
spec:
  scraperConfig: # same fields as krateoplatformops/finops-prometheus-scraper-generic
    tableName: # tableName in the database to upload the data to
    # url: # path to the exporter, optional (if missing, its taken from the exporter)
    pollingIntervalHours: # int
    scraperDatabaseConfigRef: # See above kind DatabaseConfig
      name: # name of the databaseConfigRef CR 
      namespace: # namespace of the databaseConfigRef CR
  focusSpec: # See FOCUS for field details
    region:
    availabilityZone:
    billedCost:
    billingAccountId:
    billingAccountName:
    billingCurrency:
    billingPeriodStart:
    billingPeriodEnd:
    chargeCategory:
    chargeDescription:
    chargeFrequency:
    chargeSubCategory:
    chargePeriodStart:
    chargePeriodEnd:
    effectiveCost:
    listCost:
    listUnitPrice:
    pricingCategory:
    pricingQuantity:
    pricingUnit:
    invoiceIssuer:
    provider:
    publisher:
    resourceId:
    resourceName:
    resourceType:
    serviceName:
    serviceCategory:
    subAccountId:
    subAccountName:
    skuId:
    skuPriceId:
    tags:
      - key:
        value:
    usageQuantity:
    usageUnit: 