# permissions for end users to edit focusconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: focusconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-focus
    app.kubernetes.io/part-of: operator-focus
    app.kubernetes.io/managed-by: kustomize
  name: focusconfig-editor-role
rules:
- apiGroups:
  - finops.krateo.io
  resources:
  - focusconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - finops.krateo.io
  resources:
  - focusconfigs/status
  verbs:
  - get
